import { useMemo,useState } from 'react'
import { Activity,BrainCircuit,CheckCircle2,FlaskConical,Newspaper,RefreshCw,ShieldCheck } from 'lucide-react'
import { Area,Bar,BarChart,CartesianGrid,Cell,ComposedChart,Line,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts'
import { ChartCard } from './ChartCard'
import { buildForecast,createSubcontractSiteForecasts,type ForecastContext,type ForecastScenario,type ForecastTarget } from '../services/forecastEngine'
import { approvedEventLift,sampleEventSignals,signalApplies } from '../services/eventSignalService'
import { money,percent } from '../utils'

const defaultScenario:ForecastScenario={contractGrowth:3,laborInflation:4,supplyInflation:2,churn:1}
const clientContexts:{client:string;vertical:string}[]=[{client:'All clients',vertical:'Portfolio'},{client:'Amazon',vertical:'Industrial / e-commerce'},{client:'UPS',vertical:'Industrial / parcel logistics'},{client:'Meridian Health',vertical:'Healthcare'},{client:'Summit Education',vertical:'Education'}]

export function ForecastingDashboard(){
  const [target,setTarget]=useState<ForecastTarget>('Revenue')
  const [horizon,setHorizon]=useState(12)
  const [scenario,setScenario]=useState(defaultScenario)
  const [client,setClient]=useState('All clients')
  const [signalsEnabled,setSignalsEnabled]=useState(true)
  const selectedContext=clientContexts.find(row=>row.client===client)??clientContexts[0]
  const context:ForecastContext={client:selectedContext.client,vertical:selectedContext.vertical,eventLift:approvedEventLift(selectedContext.client,selectedContext.vertical),signalsEnabled}
  const result=useMemo(()=>buildForecast(target,horizon,scenario,context),[target,horizon,scenario,client,signalsEnabled])
  const subcontractSites=useMemo(()=>createSubcontractSiteForecasts(client),[client])
  const champion=result.scores[0]
  const forecastRows=result.series.filter(point=>point.kind==='forecast')
  const chartData=result.series.map((point,index,all)=>({period:point.period,actual:point.kind==='actual'?point.value:null,forecast:point.kind==='forecast'||index===result.history.length-1?point.value:null,bandBase:point.lower95,band95:point.lower95==null?undefined:point.upper95!-point.lower95!}))
  const latest=result.history.at(-1)!.value,end=forecastRows.at(-1)!.value,growth=(end/latest-1)*100
  const update=<K extends keyof ForecastScenario>(key:K,value:number)=>setScenario(current=>({...current,[key]:value}))
  return <>
    <div className="forecast-hero"><div><h2>Forecast prototype</h2><p>Generated history · rolling-origin backtests · scenario overlay</p></div><div className="model-status model-status--demo"><span><CheckCircle2 size={14}/>Selected candidate</span><strong>{result.champion}</strong><small>Generated through {result.trainedThrough} · 48 generated observations</small></div></div>
    <div className="forecast-toolbar"><label><span>Forecast target</span><select value={target} onChange={event=>setTarget(event.target.value as ForecastTarget)}><option>Revenue</option><option>Gross profit</option><option>Labor cost</option><option>Subcontractor cost</option></select></label><label><span>Client / portfolio</span><select value={client} onChange={event=>setClient(event.target.value)}>{clientContexts.map(row=><option key={row.client}>{row.client}</option>)}</select></label><label><span>Horizon</span><select value={horizon} onChange={event=>setHorizon(Number(event.target.value))}><option value={6}>6 months</option><option value={12}>12 months</option><option value={18}>18 months</option></select></label><label className="signal-toggle"><input type="checkbox" checked={signalsEnabled} onChange={event=>setSignalsEnabled(event.target.checked)}/><span>Use approved event signals</span></label><button className="secondary-button" onClick={()=>setScenario(defaultScenario)}><RefreshCw size={14}/>Reset scenario</button></div>
    <div className="forecast-kpis"><div><span>Illustrative fit score</span><strong>{percent(100-champion.wape)}</strong><small>100 − WAPE on generated history</small></div><div><span>WAPE</span><strong>{percent(champion.wape)}</strong><small>rolling 3-month folds</small></div><div><span>Forecast bias</span><strong className={Math.abs(champion.bias)>3?'text-bad':'text-good'}>{champion.bias>=0?'+':''}{percent(champion.bias)}</strong><small>over / under prediction</small></div><div><span>Approx. 95% coverage</span><strong>{percent(champion.coverage95)}</strong><small>RMSE-based interval check</small></div><div><span>{horizon}-month change</span><strong className={growth>=0?'text-good':'text-bad'}>{growth>=0?'+':''}{percent(growth)}</strong><small>{money(latest)} to {money(end)}</small></div></div>
    <div className="dashboard-grid"><ChartCard title={`${target} forecast`} subtitle={`Actuals through ${result.trainedThrough} · ${horizon}-month forecast with 95% prediction interval`} className="span-8"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData} margin={{top:10,right:10,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="var(--grid)"/><XAxis dataKey="period" tickLine={false} axisLine={false} minTickGap={24} tick={{fontSize:10,fill:'var(--muted)'}}/><YAxis tickFormatter={value=>money(value,0)} width={55} tickLine={false} axisLine={false} tick={{fontSize:10,fill:'var(--muted)'}}/><Tooltip formatter={(value,name)=>[money(Number(value??0)),name==='band95'?'95% interval':String(name)]}/><Area dataKey="bandBase" stackId="interval" fill="transparent" stroke="none" isAnimationActive={false}/><Area dataKey="band95" stackId="interval" fill="var(--blue-soft)" fillOpacity={.7} stroke="none" isAnimationActive={false}/><Line dataKey="actual" name="Actual" stroke="var(--navy)" strokeWidth={2.5} dot={false} connectNulls={false}/><Line dataKey="forecast" name="Forecast" stroke="var(--blue)" strokeWidth={2.5} strokeDasharray="6 4" dot={false} connectNulls={false}/></ComposedChart></ResponsiveContainer></ChartCard><ChartCard title="Scenario assumptions" subtitle="Changes affect forecasts, not backtest scores" className="span-4"><div className="scenario-controls"><ScenarioSlider label="Contract growth" value={scenario.contractGrowth} min={-5} max={12} onChange={value=>update('contractGrowth',value)}/><ScenarioSlider label="Labor inflation" value={scenario.laborInflation} min={0} max={12} onChange={value=>update('laborInflation',value)}/><ScenarioSlider label="Supply inflation" value={scenario.supplyInflation} min={-2} max={12} onChange={value=>update('supplyInflation',value)}/><ScenarioSlider label="Annual churn" value={scenario.churn} min={0} max={10} onChange={value=>update('churn',value)}/><div className="scenario-note"><FlaskConical size={14}/><span>Scenario overlay is separated from the statistically fitted baseline.</span></div></div></ChartCard></div>
    <div className="dashboard-grid"><ChartCard title="Champion / challenger comparison" subtitle="Lower rolling-origin WAPE is better" className="span-6"><ResponsiveContainer width="100%" height="100%"><BarChart data={result.scores} layout="vertical" margin={{left:8,right:22}}><CartesianGrid horizontal={false} stroke="var(--grid)"/><XAxis type="number" unit="%" domain={[0,'dataMax']} tick={{fontSize:10,fill:'var(--muted)'}}/><YAxis type="category" dataKey="model" width={108} axisLine={false} tickLine={false} tick={{fontSize:10,fill:'var(--text)'}}/><Tooltip formatter={(value)=>percent(Number(value??0))}/><Bar dataKey="wape" radius={[0,5,5,0]}>{result.scores.map((row,index)=><Cell key={row.model} fill={index===0?'var(--blue)':'var(--blue-soft)'}/>)}</Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Forecast drivers" subtitle="Relative modeled influence · direction shown separately" className="span-6"><div className="driver-list">{result.drivers.map(driver=><div key={driver.name}><div><span>{driver.name}</span><b className={driver.direction==='positive'?'text-good':'text-bad'}>{driver.direction==='positive'?'+':'−'} {driver.impact}%</b></div><i><em style={{width:`${driver.impact}%`}}/></i></div>)}</div></ChartCard></div>
    <ChartCard title="External event and vertical signal ledger" subtitle={`Illustrative governed feed · ${selectedContext.vertical} · approved lift ${signalsEnabled?percent(context.eventLift):'excluded'}`}><div className="signal-ledger-intro"><Newspaper size={16}/><span>Only approved, time-bounded signals with a source and a confidence enter the model.</span></div><div className="detail-table-wrap"><table className="detail-table"><thead><tr><th>Scope</th><th>Signal</th><th>Source type</th><th>Effective window</th><th>Modeled lift</th><th>Confidence</th><th>State</th></tr></thead><tbody>{sampleEventSignals.map(row=><tr key={row.id} className={!signalApplies(row,client,selectedContext.vertical)?'muted-row':''}><td><strong>{row.scope}</strong><span>{row.mode} · as of {row.asOf}</span></td><td>{row.signal}</td><td>{row.source}</td><td>{row.effectiveWindow}</td><td className={row.lift>=0?'text-good':'text-bad'}>{row.lift>=0?'+':''}{percent(row.lift)}</td><td>{percent(row.confidence)}</td><td><span className={`validation-state ${row.status==='Approved'?'validation-state--pass':'validation-state--watch'}`}>{row.status}</span></td></tr>)}</tbody></table></div></ChartCard>
    {target==='Subcontractor cost'&&<ChartCard title="Subcontracted site cost forecast" subtitle="Prior approved invoice history + vendor trend + approved client and vertical events"><div className="detail-table-wrap"><table className="detail-table"><thead><tr><th>Client / site</th><th>Vertical</th><th>Invoice history</th><th>Last invoice</th><th>3-month average</th><th>Vendor trend</th><th>Event lift</th><th>Next-quarter forecast</th><th>Confidence</th></tr></thead><tbody>{subcontractSites.map(row=><tr key={row.site}><td><strong>{row.client}</strong><span>{row.site}</span></td><td>{row.vertical}</td><td>{row.invoiceMonths} months</td><td>{money(row.lastInvoice)}</td><td>{money(row.threeMonthAverage)}</td><td className="text-bad">+{percent(row.trend)}</td><td className={row.eventLift>=0?'text-bad':'text-good'}>{row.eventLift>=0?'+':''}{percent(row.eventLift)}</td><td><strong>{money(row.nextQuarter)}</strong></td><td>{percent(row.confidence)}</td></tr>)}</tbody></table></div></ChartCard>}
    <ChartCard title="Rolling-origin backtest" subtitle="Six non-overlapping 3-month holdout windows; no future observations used in training"><div className="detail-table-wrap"><table className="detail-table"><thead><tr><th>Training cutoff</th><th>Holdout horizon</th><th>Actual</th><th>Predicted</th><th>WAPE</th><th>Bias</th><th>Result</th></tr></thead><tbody>{result.folds.map(fold=><tr key={fold.origin}><td>{fold.origin}</td><td>{fold.horizon} months</td><td>{money(fold.actual)}</td><td>{money(fold.predicted)}</td><td>{percent(fold.wape)}</td><td className={Math.abs(fold.bias)>3?'text-bad':'text-good'}>{fold.bias>=0?'+':''}{percent(fold.bias)}</td><td><span className={`validation-state ${fold.wape<8?'validation-state--pass':'validation-state--watch'}`}>{fold.wape<8?'Pass':'Monitor'}</span></td></tr>)}</tbody></table></div></ChartCard>
    <div className="governance-heading"><div><span>Target production controls</span><strong>Planned capabilities—not active services in this demo</strong></div></div><div className="governance-grid governance-grid--planned"><div><BrainCircuit/><span>Model registry</span><strong>Planned</strong><small>Persisted versions, lineage, and promotion status</small></div><div><ShieldCheck/><span>Validation policy</span><strong>Proposed thresholds</strong><small>FP&amp;A approval required before promotion</small></div><div><Activity/><span>Drift monitoring</span><strong>Planned</strong><small>Feature, residual, and coverage alerts</small></div><div><CheckCircle2/><span>Reproducibility</span><strong>Planned</strong><small>Versioned data, assumptions, and run audit trail</small></div></div>
  </>
}

function ScenarioSlider({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(value:number)=>void}){return <label className="scenario-slider"><span>{label}<b>{value.toFixed(1)}%</b></span><input type="range" min={min} max={max} step={.5} value={value} onChange={event=>onChange(Number(event.target.value))}/></label>}
