import {useMemo,useState} from 'react'
import {Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {monthlyPerformance} from '../data/seed'
import type {JobSite} from '../types'
import {money,number,percent,sum} from '../utils'
import {ChartCard} from './ChartCard'

const palette=['#378add','#1d9e75','#d85a30','#7f77dd','#ba7517','#0f828c','#d4537e','#5f6b7a']

interface AccountRow{account:string;jobs:JobSite[];revenue:number;labor:number;budget:number;hours:number;scheduled:number;overtime:number;color:string}

function summarize(jobs:JobSite[],account:string,color:string):AccountRow{return {account,jobs,revenue:sum(jobs,j=>j.revenue),labor:sum(jobs,j=>j.labor),budget:sum(jobs,j=>j.laborBudget),hours:sum(jobs,j=>j.actualHours),scheduled:sum(jobs,j=>j.scheduledHours),overtime:sum(jobs,j=>j.overtimeHours),color}}
const state=(actual:number,target:number)=>actual>target+3?'High':actual>target?'Watch':'On track'

export function LaborDashboard({jobs}:{jobs:JobSite[]}){
  const accounts=useMemo(()=>Object.entries(jobs.reduce<Record<string,JobSite[]>>((rows,job)=>{(rows[job.customer]??=[]).push(job);return rows},{})).map(([account,sites],index)=>summarize(sites,account,palette[index%palette.length])).sort((a,b)=>b.labor-a.labor),[jobs])
  const [selected,setSelected]=useState('All accounts')
  const activeJobs=selected==='All accounts'?jobs:jobs.filter(job=>job.customer===selected)
  const active=summarize(activeJobs,selected,'#378add')
  const laborPct=active.revenue?active.labor/active.revenue*100:0,targetPct=active.revenue?active.budget/active.revenue*100:0,variance=active.labor-active.budget
  const verdict=state(laborPct,targetPct),range=Math.max(laborPct,targetPct)*1.15||1
  const hourlyCost=active.hours?active.labor/active.hours:0,otCost=active.overtime*hourlyCost*1.5
  const overallPct=sum(jobs,j=>j.labor)/sum(jobs,j=>j.revenue)*100
  const trend=monthlyPerformance.map((row,index)=>({month:row.month,laborPct:+((row.labor/row.revenue)*(laborPct/overallPct)*100).toFixed(1),target:+targetPct.toFixed(1),otCost:Math.round(otCost*(.82+index*.022+Math.sin(index*.82)*.06))}))
  const visibleAccounts=selected==='All accounts'?accounts:accounts.filter(row=>row.account===selected)
  const cardAccounts=selected==='All accounts'?[...accounts].sort((a,b)=>(b.labor/b.budget)-(a.labor/a.budget)).slice(0,4):visibleAccounts
  const accountTrends=accounts.slice(0,4).map(row=>({row,data:monthlyPerformance.map((month,index)=>({month:month.month,value:+((row.labor/row.revenue*100)*(.94+index*.006+Math.sin(index*.72)*.025)).toFixed(1),target:+(row.budget/row.revenue*100).toFixed(1)}))}))
  const siteRows=[...activeJobs].sort((a,b)=>(b.actualHours-b.scheduledHours)-(a.actualHours-a.scheduledHours))
  return <div className="labor-reference-view">
    <div className="data-notice"><strong>Demo account view</strong><span>Current-period totals use seeded site records. T12M account patterns and estimated overtime cost are illustrative until source history is connected.</span></div>
    <label className="account-select"><span>Account</span><select value={selected} onChange={event=>setSelected(event.target.value)}><option>All accounts</option>{accounts.map(row=><option key={row.account}>{row.account}</option>)}</select></label>
    <div className="account-tabs" role="tablist" aria-label="Labor account view"><button role="tab" aria-selected={selected==='All accounts'} className={selected==='All accounts'?'active':''} onClick={()=>setSelected('All accounts')}>All accounts</button>{accounts.map(row=><button role="tab" aria-selected={selected===row.account} key={row.account} className={selected===row.account?'active':''} onClick={()=>setSelected(row.account)}>{row.account}</button>)}</div>
    <section className="labor-combo">
      <div className="labor-combo__top"><div><strong>{selected==='All accounts'?'Combined labor portfolio':selected}</strong><span>{activeJobs.length} sites · budget-weighted target {percent(targetPct)}</span></div><b className={`labor-verdict labor-verdict--${verdict==='High'?'bad':verdict==='Watch'?'watch':'ok'}`}>{verdict==='On track'?`${percent(targetPct-laborPct)} under target`:`${percent(laborPct-targetPct)} over target`}</b></div>
      <div className="labor-combo__kpis"><div><span>Total labor</span><strong>{money(active.labor)}</strong><small className={variance>0?'text-bad':'text-good'}>{variance>=0?'+':''}{money(variance)} vs budget</small></div><div><span>Revenue</span><strong>{money(active.revenue)}</strong><small>{activeJobs.length} active sites</small></div><div><span>Labor %</span><strong className={verdict==='On track'?'text-good':'text-bad'}>{percent(laborPct)}</strong><small>{verdict}</small></div><div><span>Target</span><strong>{percent(targetPct)}</strong><small>≤ is favorable</small></div><div><span>OT cost</span><strong>{money(otCost)}</strong><small>{number(active.overtime)} overtime hours</small></div></div>
      <div className="labor-target-track"><i style={{width:`${Math.min(100,laborPct/range*100)}%`}} className={verdict==='On track'?'is-good':'is-bad'}/><em style={{left:`${Math.min(100,targetPct/range*100)}%`}}/></div>
    </section>
    <div className="dashboard-grid"><ChartCard title="Labor % of revenue · illustrative trend" subtitle={`${selected} · indexed T12M pattern · target shown as dashed reference`} className="span-8"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend} margin={{top:8,right:12,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="var(--grid)"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:10,fill:'var(--muted)'}}/><YAxis domain={['dataMin - 4','dataMax + 4']} tickFormatter={v=>`${v}%`} width={38} axisLine={false} tickLine={false} tick={{fontSize:10,fill:'var(--muted)'}}/><Tooltip formatter={(v,name)=>[percent(Number(v??0)),name==='target'?'Target':'Labor %']}/><Line dataKey="laborPct" stroke="#378add" strokeWidth={2.5} dot={{r:2}} activeDot={{r:4}}/><Line dataKey="target" stroke="var(--text)" strokeWidth={1.2} strokeDasharray="5 4" dot={false}/></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Overtime cost · illustrative trend" subtitle={`${selected} · estimate uses hours × blended hourly cost × 1.5`} className="span-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={trend}><CartesianGrid vertical={false} stroke="var(--grid)"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:9,fill:'var(--muted)'}}/><YAxis tickFormatter={v=>money(v,0)} width={48} axisLine={false} tickLine={false} tick={{fontSize:9,fill:'var(--muted)'}}/><Tooltip formatter={v=>money(Number(v??0))}/><Bar dataKey="otCost" fill="#d85a30" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></ChartCard></div>
    <div className="labor-section-heading"><h2>{selected==='All accounts'?'Highest labor variance accounts':`${selected} operating summary`}</h2><span>{selected==='All accounts'?'Four accounts furthest above plan':'Selected account detail'}</span></div>
    <div className="labor-account-grid">{cardAccounts.map(row=>{const lp=row.labor/row.revenue*100,target=row.budget/row.revenue*100,label=state(lp,target);return <section key={row.account} className="labor-account-card"><header><strong><i className="account-color" style={{background:row.color}}/>{row.account}</strong><span style={{background:`${row.color}18`,color:row.color}}>{row.jobs.length} sites</span></header><div><article><small>Labor cost</small><b>{money(row.labor)}</b><em className={row.labor>row.budget?'text-bad':'text-good'}>{row.labor>row.budget?'+':''}{percent((row.labor/row.budget-1)*100)} vs plan</em></article><article><small>Revenue</small><b>{money(row.revenue)}</b><em>{money(row.revenue/row.jobs.length)} / site</em></article><article><small>Labor %</small><b>{percent(lp)}</b><em className={label==='On track'?'text-good':'text-bad'}>{label} · target {percent(target)}</em></article><article><small>OT cost</small><b>{money(row.overtime*(row.labor/row.hours)*1.5)}</b><em>{number(row.overtime)} hours</em></article></div><div className="labor-account-card__sites">{row.jobs.map(site=><span key={site.id}>{site.name}</span>)}</div></section>})}</div>
    {selected==='All accounts'&&<div className="labor-small-multiples">{accountTrends.map(({row,data})=><section key={row.account}><header><strong style={{color:row.color}}>{row.account}</strong><span>{percent(row.labor/row.revenue*100)} current</span></header><ResponsiveContainer width="100%" height={145}><LineChart data={data} margin={{top:8,right:8,left:-14,bottom:0}}><CartesianGrid vertical={false} stroke="var(--grid)"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:8,fill:'var(--muted)'}}/><YAxis domain={['dataMin - 3','dataMax + 3']} tickFormatter={v=>`${v}%`} axisLine={false} tickLine={false} tick={{fontSize:8,fill:'var(--muted)'}}/><Line dataKey="value" stroke={row.color} strokeWidth={2} dot={false}/><Line dataKey="target" stroke="var(--text)" strokeWidth={1} strokeDasharray="3 3" dot={false}/></LineChart></ResponsiveContainer></section>)}</div>}
    <ChartCard title="Account summary" subtitle="Exact values for the current reporting period"><div className="detail-table-wrap"><table className="detail-table"><thead><tr><th>Account</th><th>Sites</th><th>Revenue</th><th>Labor cost</th><th>Budget</th><th>Variance</th><th>Labor %</th><th>Target</th><th>OT hours</th></tr></thead><tbody>{visibleAccounts.map(row=><tr key={row.account}><td><strong><i className="account-color" style={{background:row.color}}/>{row.account}</strong></td><td>{row.jobs.length}</td><td>{money(row.revenue)}</td><td>{money(row.labor)}</td><td>{money(row.budget)}</td><td className={row.labor>row.budget?'text-bad':'text-good'}>{row.labor>row.budget?'+':''}{money(row.labor-row.budget)}</td><td>{percent(row.labor/row.revenue*100)}</td><td>{percent(row.budget/row.revenue*100)}</td><td>{number(row.overtime)}</td></tr>)}</tbody></table></div></ChartCard>
    <ChartCard title="Sites over labor budget" subtitle="Worked hours and overtime compared with scheduled allowance"><div className="hours-cut-legend"><span><i className="worked"/>Regular hours</span><span><i className="overtime"/>Overtime hours</span><span><i className="allowance"/>Scheduled allowance</span></div><div className="hours-cut-list">{siteRows.map(site=>{const max=Math.max(site.actualHours,site.scheduledHours)*1.12,regular=Math.max(0,site.actualHours-site.overtimeHours),over=Math.max(0,site.actualHours-site.scheduledHours);return <div key={site.id} className="hours-cut-row"><div><strong>{site.name}</strong><span>{site.customer} · {site.branch}</span><b className={over>0?'text-bad':'text-good'}>{over>0?`${number(over)}h to cut`:'Within allowance'}</b></div><div className="hours-cut-track"><i className="worked" style={{width:`${regular/max*100}%`}}/><i className="overtime" style={{width:`${site.overtimeHours/max*100}%`}}/><em style={{left:`${site.scheduledHours/max*100}%`}}/></div><small>{number(site.actualHours)}h worked · {number(site.scheduledHours)}h allowance · {number(site.overtimeHours)}h OT</small></div>})}</div></ChartCard>
  </div>
}
